### ISSUE TITLE
Archlinux: salt detects upstart so service.running fails 

### ISSUE THREAD

**Issue by noelmcloughlin** [saltstack-formulas/tomcat-formula#68]
Function **service.running** fails on Archlinux.

```
          ID: tomcat
    Function: service.running
        Name: tomcat8
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/site-packages/salt/state.py", line 1837, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1794, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/site-packages/salt/states/service.py", line 887, in mod_watch
                  __salt__['service.stop'](name)
                File "/usr/lib/python2.7/site-packages/salt/modules/service.py", line 119, in stop
                  return __salt__['service.run'](name, 'stop')
                File "/usr/lib/python2.7/site-packages/salt/modules/service.py", line 93, in run
                  return not __salt__['cmd.retcode'](cmd, python_shell=False)
                File "/usr/lib/python2.7/site-packages/salt/modules/cmdmod.py", line 1882, in retcode
                  **kwargs)
                File "/usr/lib/python2.7/site-packages/salt/modules/cmdmod.py", line 564, in _run
                  raise CommandExecutionError(msg)
              CommandExecutionError: Unable to run command '['/etc/init.d/tomcat8', 'stop']' 
           <<cut>>
 reason: command not found
```

**Comment by noelmcloughlin** [comment]
Should work already? saltstack/salt#27841  but its not: [Uploading tomcat_manjaro_testresult.log.txt…]()
